name: test.yml
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Docker Compose
        uses: docker/setup-compose-action@v1
      - name: Start Docker Environment
        run: |
          docker compose up -d
      - name: Run Tests
        run: |
          docker compose run test balder --working-dir tests --junit=result.xml
      - name: Cleanup Docker
        if: always()
        run: |
          docker compose down
        
